# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-thumbfast-osc = {
    pname = "mpv-thumbfast-osc";
    version = "5fefc9b8e995cf5e663666aa10649af799e60186";
    src = fetchFromGitHub {
      owner = "po5";
      repo = "thumbfast";
      rev = "5fefc9b8e995cf5e663666aa10649af799e60186";
      fetchSubmodules = false;
      sha256 = "sha256-6nICOdtPzDQUMufqCJ+g2OnPasOgp3PegnRoWw8TVBU=";
    };
    date = "2023-12-21";
  };
}
