# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-thumbfast-osc = {
    pname = "mpv-thumbfast-osc";
    version = "fb9d37e76b97a3a541004556ec19c0620ca308a3";
    src = fetchFromGitHub {
      owner = "po5";
      repo = "thumbfast";
      rev = "fb9d37e76b97a3a541004556ec19c0620ca308a3";
      fetchSubmodules = false;
      sha256 = "sha256-rVXjIoYxHOG4eDpQ1ls3L6UhYsmmZ014hzQOIRBS+uk=";
    };
    date = "2023-11-11";
  };
}
