# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  tenki = {
    pname = "tenki";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "ckaznable";
      repo = "tenki";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-64yNMO+Tm8APF2NnygQuub4z7kCxxf+T1urgA4Qs104=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./tenki-v1.4.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
}
