# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-smartskip = {
    pname = "mpv-smartskip";
    version = "48d68283cea47ff8e904decc9003b3abc3e2123e";
    src = fetchFromGitHub {
      owner = "Eisa01";
      repo = "mpv-scripts";
      rev = "48d68283cea47ff8e904decc9003b3abc3e2123e";
      fetchSubmodules = false;
      sha256 = "sha256-95CAKjBRELX2f7oWSHFWJnI0mikAoxhfUphe9k51Qf4=";
    };
    date = "2023-11-25";
  };
}
