[backdrop]
enabled = true

[bar.default]
background_opacity = 0.5
capsule_thickness = 0.75
center = ["workspaces"]
end = ["battery", "volume", "clock"]
margin_edge = 0
margin_ends = 0
padding = 13
radius = 0
start = ["control-center"]
thickness = 30
widget_spacing = 16

[bar.default.dead_zone]
middle_command = "toggle-speaker"
scroll_down_command = "noctalia msg volume-down 1"
scroll_up_command = "noctalia msg volume-up 1"

[control_center]
sidebar_section = "none"

[desktop_widgets]
enabled = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

[location]
auto_locate = true

[lockscreen]
fingerprint = false
blur_intensity = 0.0
tint_intensity = 0.3

[lockscreen_widgets]
enabled = true
schema_version = 2

[lockscreen_widgets.grid]
cell_size = 64
major_interval = 4
visible = true

[notification]
scale = 0.9
show_actions = false
show_app_name = false

[osd.kinds]
media = false

[shell]
avatar_path = "/home/iynaix/.face"
font_family = "Geist Medium"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true

[shell.launcher]
categories = false
session_search = true
sort_by_usage = false

[shell.panel]
open_near_click_control_center = true
session_placement = "floating"
session_position = "center"
transparency_mode = "glass"

[[shell.session.actions]]
action = "shutdown"
countdown_seconds = 0.0
enabled = true
shortcut = "1"
variant = "destructive"

[[shell.session.actions]]
action = "reboot"
countdown_seconds = 0.0
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "lock"
countdown_seconds = 0.0
enabled = false
shortcut = "5"
variant = "default"

[[shell.session.actions]]
action = "logout"
countdown_seconds = 0.0
enabled = true
shortcut = "3"
variant = "default"

[[shell.session.actions]]
action = "lock_and_suspend"
countdown_seconds = 0.0
enabled = true
shortcut = "4"
variant = "default"

[theme]
source = "wallpaper"

[theme.templates]
builtin_ids = [ "btop", "cava", "ghostty", "hyprland", "mango", "niri" ]
community_ids = [ "yazi", "zathura" ]

[widget.battery]
color = "primary"
icon_color = "primary"

[widget.clock]
color = "primary"

[widget.control-center]
custom_image = "/persist/home/iynaix/projects/dotfiles/modules/gui/gtk/icons/nix.svg"
custom_image_colorize = true
glyph = ""

[widget.session]
custom_image = "/persist/home/iynaix/projects/dotfiles/modules/gui/gtk/icons/nix.svg"
glyph = ""
icon_color = "primary"

[widget.volume]
color = "primary"
scroll_step = 1

[widget.workspaces]
display = "name"
enabled = true
font_family = "Liberation Sans"
font_weight = 700
labels_only_when_occupied = true
pill_scale = 0.8
