{
  lib,
  user,
  ...
}: {
  options.iynaix = {
    pywal.enable = lib.mkEnableOption "pywal" // {default = true;};
  };

  config = {
    home-manager.users.${user} = {
      programs.pywal.enable = true;

      # TODO: helix?

      xdg.configFile."wal/templates/colors-hexless.sh".text = ''
        # Shell variables
        # Generated by 'wal'
        wallpaper="{wallpaper}"

        # Special
        background='{background.strip}'
        foreground='{foreground.strip}'
        cursor='{cursor.strip}'

        # Colors
        color0='{color0.strip}'
        color1='{color1.strip}'
        color2='{color2.strip}'
        color3='{color3.strip}'
        color4='{color4.strip}'
        color5='{color5.strip}'
        color6='{color6.strip}'
        color7='{color7.strip}'
        color8='{color8.strip}'
        color9='{color9.strip}'
        color10='{color10.strip}'
        color11='{color11.strip}'
        color12='{color12.strip}'
        color13='{color13.strip}'
        color14='{color14.strip}'
        color15='{color15.strip}'

        # FZF colors
        export FZF_DEFAULT_OPTS="
            $FZF_DEFAULT_OPTS
            --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
            --color info:7,prompt:2,spinner:1,pointer:232,marker:1
        "

        # Fix LS_COLORS being unreadable.
        export LS_COLORS="''${{LS_COLORS}}:su=30;41:ow=30;42:st=30;44:"
      '';
    };

    iynaix.persist.home.directories = [
      ".config/wal"
      ".cache/wal"
    ];
  };
}
