# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  vv = {
    pname = "vv";
    version = "1.9.2.1";
    src = fetchFromGitHub {
      owner = "hackerb9";
      repo = "vv";
      rev = "1.9.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-uN7MVasU2oFqKa94GcdB3R3Xt+9aVOKX6LWFPwfW80Y=";
    };
  };
}
