# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  awakened-poe-trade = {
    pname = "awakened-poe-trade";
    version = "3.28.103";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.28.103/Awakened-PoE-Trade-3.28.103.AppImage";
      sha256 = "sha256-p/XDWnE9lm/LwT3r/lhQWtEJ3YoaGRFd4Rv7RbdDIeg=";
    };
  };
  exiled-exchange-2 = {
    pname = "exiled-exchange-2";
    version = "0.13.10";
    src = fetchurl {
      url = "https://github.com/Kvan7/Exiled-Exchange-2/releases/download/v0.13.10/Exiled-Exchange-2-0.13.10.AppImage";
      sha256 = "sha256-mQNUJptaObbEMtBLCgJn7A6nmgVpl4o0JWTg6FH20U0=";
    };
  };
  helium = {
    pname = "helium";
    version = "0.10.6.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.10.6.1/helium-0.10.6.1-x86_64.AppImage";
      sha256 = "sha256-6xqNRaP3aqitEseexRVEEjKkJClC0j1HHZoRGQanhSk=";
    };
  };
  mango = {
    pname = "mango";
    version = "0.12.7";
    src = fetchFromGitHub {
      owner = "mangowm";
      repo = "mango";
      rev = "0.12.7";
      fetchSubmodules = false;
      sha256 = "sha256-dkqs7Bk3099dLGY6x9/Mp6lpieFJ8tKAe6wr59CknMc=";
    };
  };
  mpv-deletefile = {
    pname = "mpv-deletefile";
    version = "62f4bb313c6cb6366672e78dea940e9da8fec84a";
    src = fetchFromGitHub {
      owner = "zenyd";
      repo = "mpv-scripts";
      rev = "62f4bb313c6cb6366672e78dea940e9da8fec84a";
      fetchSubmodules = false;
      sha256 = "sha256-9gO+GkNoGsxAbMRrBWu0FfXEQtyTmHivlaxlYLpV2YM=";
    };
    date = "2025-12-06";
  };
  mpv-sub-select = {
    pname = "mpv-sub-select";
    version = "26d24a0fd1d69988eaedda6056a2c87d0a55b6cb";
    src = fetchFromGitHub {
      owner = "CogentRedTester";
      repo = "mpv-sub-select";
      rev = "26d24a0fd1d69988eaedda6056a2c87d0a55b6cb";
      fetchSubmodules = false;
      sha256 = "sha256-+eVga4b7KIBnfrtmlgq/0HNjQVS3SK6YWVXCPvOeOOc=";
    };
    date = "2025-04-04";
  };
  niri = {
    pname = "niri";
    version = "d06dd4b9e60fa07120c217aa095f3ed8caac99f2";
    src = fetchFromGitHub {
      owner = "YaLTeR";
      repo = "niri";
      rev = "d06dd4b9e60fa07120c217aa095f3ed8caac99f2";
      fetchSubmodules = false;
      sha256 = "sha256-L/Ldq9G41Mj8WjWTuC+rePvWIx1A/tHdFpLbQmtrMSA=";
    };
    date = "2026-03-22";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "093c1a79f58daab358199c4246de50357e5bf462";
    src = fetchFromGitHub {
      owner = "adi1090x";
      repo = "rofi";
      rev = "093c1a79f58daab358199c4246de50357e5bf462";
      fetchSubmodules = false;
      sha256 = "sha256-iUX0Quae06tGd7gDgXZo1B3KYgPHU+ADPBrowHlv02A=";
    };
    date = "2025-07-26";
  };
  rusty-path-of-building = {
    pname = "rusty-path-of-building";
    version = "v0.2.15";
    src = fetchFromGitHub {
      owner = "meehl";
      repo = "rusty-path-of-building";
      rev = "v0.2.15";
      fetchSubmodules = false;
      sha256 = "sha256-YhCJkyzWVZ1BEux85qyTHlyLS/LaotMoe+tGwwd9EOI=";
    };
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "196281844b8cbcac658a59013e4805300c2d6126";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "196281844b8cbcac658a59013e4805300c2d6126";
      fetchSubmodules = false;
      sha256 = "sha256-pAkBlodci4Yf+CTjhGuNtgLOTMNquty7xP0/HSeoLzE=";
    };
    date = "2026-02-27";
  };
  yazi-time-travel = {
    pname = "yazi-time-travel";
    version = "aaec6e26e525bd146354a5137ec40f1f23257a4e";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "time-travel.yazi";
      rev = "aaec6e26e525bd146354a5137ec40f1f23257a4e";
      fetchSubmodules = false;
      sha256 = "sha256-/+KiuGUox763dMQvHl1l3+Ci3vL8NwRuKNu9pi3gjyE=";
    };
    date = "2026-01-16";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "2026.03.17";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "2026.03.17";
      fetchSubmodules = false;
      sha256 = "sha256-A4LUCuKCjpVAOJ8jNoYaC3mRCiKH0/wtcsle0YfZyTA=";
    };
  };
}
