# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  awakened-poe-trade = {
    pname = "awakened-poe-trade";
    version = "3.27.106";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.27.106/Awakened-PoE-Trade-3.27.106.AppImage";
      sha256 = "sha256-8L5Szn0KYfUMaTe+yyhJV1YZspmJCSlXSHXLPoiRhjE=";
    };
  };
  exiled-exchange-2 = {
    pname = "exiled-exchange-2";
    version = "0.13.10";
    src = fetchurl {
      url = "https://github.com/Kvan7/Exiled-Exchange-2/releases/download/v0.13.10/Exiled-Exchange-2-0.13.10.AppImage";
      sha256 = "sha256-mQNUJptaObbEMtBLCgJn7A6nmgVpl4o0JWTg6FH20U0=";
    };
  };
  helium = {
    pname = "helium";
    version = "0.8.5.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.8.5.1/helium-0.8.5.1-x86_64.AppImage";
      sha256 = "sha256-jFSLLDsHB/NiJqFmn8S+JpdM8iCy3Zgyq+8l4RkBecM=";
    };
  };
  mango = {
    pname = "mango";
    version = "0.12.2";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "mangowc";
      rev = "0.12.2";
      fetchSubmodules = false;
      sha256 = "sha256-B70RXGpG2sH6WuP4XFdijgsZm39LEFIh0h/5E0r99W4=";
    };
  };
  mpv-cut = {
    pname = "mpv-cut";
    version = "3b18f1161ffb2ff822c88cb97e099772d4b3c26d";
    src = fetchFromGitHub {
      owner = "familyfriendlymikey";
      repo = "mpv-cut";
      rev = "3b18f1161ffb2ff822c88cb97e099772d4b3c26d";
      fetchSubmodules = false;
      sha256 = "sha256-c4NHJM1qeXXBz8oyGUzS9QiAzRYiNKjmArM1K0Q2Xo0=";
    };
    date = "2023-11-22";
  };
  mpv-deletefile = {
    pname = "mpv-deletefile";
    version = "62f4bb313c6cb6366672e78dea940e9da8fec84a";
    src = fetchFromGitHub {
      owner = "zenyd";
      repo = "mpv-scripts";
      rev = "62f4bb313c6cb6366672e78dea940e9da8fec84a";
      fetchSubmodules = false;
      sha256 = "sha256-9gO+GkNoGsxAbMRrBWu0FfXEQtyTmHivlaxlYLpV2YM=";
    };
    date = "2025-12-06";
  };
  mpv-nextfile = {
    pname = "mpv-nextfile";
    version = "b8f7a4d6224876bf26724a9313a36e84d9ecfd81";
    src = fetchFromGitHub {
      owner = "jonniek";
      repo = "mpv-nextfile";
      rev = "b8f7a4d6224876bf26724a9313a36e84d9ecfd81";
      fetchSubmodules = false;
      sha256 = "sha256-Ad98iUbumhsudGwHcYEVTV6ye6KHj5fHAx8q90UQ2QM=";
    };
    date = "2023-08-09";
  };
  mpv-sub-select = {
    pname = "mpv-sub-select";
    version = "26d24a0fd1d69988eaedda6056a2c87d0a55b6cb";
    src = fetchFromGitHub {
      owner = "CogentRedTester";
      repo = "mpv-sub-select";
      rev = "26d24a0fd1d69988eaedda6056a2c87d0a55b6cb";
      fetchSubmodules = false;
      sha256 = "sha256-+eVga4b7KIBnfrtmlgq/0HNjQVS3SK6YWVXCPvOeOOc=";
    };
    date = "2025-04-04";
  };
  mpv-subsearch = {
    pname = "mpv-subsearch";
    version = "9a5cda4fc8f0896cec27dca60a32251009c0e9c5";
    src = fetchFromGitHub {
      owner = "kelciour";
      repo = "mpv-scripts";
      rev = "9a5cda4fc8f0896cec27dca60a32251009c0e9c5";
      fetchSubmodules = false;
      sha256 = "sha256-BRyKJeXWFhsCDKTUNKsp+yqYpP9mzbaZMviUFXyA308=";
    };
    date = "2019-01-24";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "093c1a79f58daab358199c4246de50357e5bf462";
    src = fetchFromGitHub {
      owner = "adi1090x";
      repo = "rofi";
      rev = "093c1a79f58daab358199c4246de50357e5bf462";
      fetchSubmodules = false;
      sha256 = "sha256-iUX0Quae06tGd7gDgXZo1B3KYgPHU+ADPBrowHlv02A=";
    };
    date = "2025-07-26";
  };
  rusty-path-of-building = {
    pname = "rusty-path-of-building";
    version = "v0.2.10";
    src = fetchFromGitHub {
      owner = "meehl";
      repo = "rusty-path-of-building";
      rev = "v0.2.10";
      fetchSubmodules = false;
      sha256 = "sha256-odiiYWoBfcnPNfXsxj0gt/ra6Z3zeBQdWRjF7BazffY=";
    };
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "88990a6cf1d31afd9d8db1a0d74bf37ef50d6786";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "88990a6cf1d31afd9d8db1a0d74bf37ef50d6786";
      fetchSubmodules = false;
      sha256 = "sha256-0K6qGgbGt8N6HgGNEmn2FDLar6hCPiPBbvOsrTjSubM=";
    };
    date = "2026-02-06";
  };
  yazi-time-travel = {
    pname = "yazi-time-travel";
    version = "aaec6e26e525bd146354a5137ec40f1f23257a4e";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "time-travel.yazi";
      rev = "aaec6e26e525bd146354a5137ec40f1f23257a4e";
      fetchSubmodules = false;
      sha256 = "sha256-/+KiuGUox763dMQvHl1l3+Ci3vL8NwRuKNu9pi3gjyE=";
    };
    date = "2026-01-16";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "2026.02.04";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "2026.02.04";
      fetchSubmodules = false;
      sha256 = "sha256-KXnz/ocHBftenDUkCiFoBRBxi6yWt0fNuRX+vKFWDQw=";
    };
  };
}
