# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  awakened-poe-trade = {
    pname = "awakened-poe-trade";
    version = "3.27.106";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.27.106/Awakened-PoE-Trade-3.27.106.AppImage";
      sha256 = "sha256-8L5Szn0KYfUMaTe+yyhJV1YZspmJCSlXSHXLPoiRhjE=";
    };
  };
  exiled-exchange-2 = {
    pname = "exiled-exchange-2";
    version = "0.13.8";
    src = fetchurl {
      url = "https://github.com/Kvan7/Exiled-Exchange-2/releases/download/v0.13.8/Exiled-Exchange-2-0.13.8.AppImage";
      sha256 = "sha256-jA/VXMi+VJmRcHRBgnt71PLvGrSBe2S2KmUtrQlIFjk=";
    };
  };
  helium = {
    pname = "helium";
    version = "0.7.7.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.7.7.1/helium-0.7.7.1-x86_64.AppImage";
      sha256 = "sha256-qEHUFzCwsCyFNLFCC62wo2x1lr/boAI/UDsaaNP1vrc=";
    };
  };
  mpv-cut = {
    pname = "mpv-cut";
    version = "3b18f1161ffb2ff822c88cb97e099772d4b3c26d";
    src = fetchFromGitHub {
      owner = "familyfriendlymikey";
      repo = "mpv-cut";
      rev = "3b18f1161ffb2ff822c88cb97e099772d4b3c26d";
      fetchSubmodules = false;
      sha256 = "sha256-c4NHJM1qeXXBz8oyGUzS9QiAzRYiNKjmArM1K0Q2Xo0=";
    };
    date = "2023-11-22";
  };
  mpv-deletefile = {
    pname = "mpv-deletefile";
    version = "62f4bb313c6cb6366672e78dea940e9da8fec84a";
    src = fetchFromGitHub {
      owner = "zenyd";
      repo = "mpv-scripts";
      rev = "62f4bb313c6cb6366672e78dea940e9da8fec84a";
      fetchSubmodules = false;
      sha256 = "sha256-9gO+GkNoGsxAbMRrBWu0FfXEQtyTmHivlaxlYLpV2YM=";
    };
    date = "2025-12-06";
  };
  mpv-nextfile = {
    pname = "mpv-nextfile";
    version = "b8f7a4d6224876bf26724a9313a36e84d9ecfd81";
    src = fetchFromGitHub {
      owner = "jonniek";
      repo = "mpv-nextfile";
      rev = "b8f7a4d6224876bf26724a9313a36e84d9ecfd81";
      fetchSubmodules = false;
      sha256 = "sha256-Ad98iUbumhsudGwHcYEVTV6ye6KHj5fHAx8q90UQ2QM=";
    };
    date = "2023-08-09";
  };
  mpv-sub-select = {
    pname = "mpv-sub-select";
    version = "26d24a0fd1d69988eaedda6056a2c87d0a55b6cb";
    src = fetchFromGitHub {
      owner = "CogentRedTester";
      repo = "mpv-sub-select";
      rev = "26d24a0fd1d69988eaedda6056a2c87d0a55b6cb";
      fetchSubmodules = false;
      sha256 = "sha256-+eVga4b7KIBnfrtmlgq/0HNjQVS3SK6YWVXCPvOeOOc=";
    };
    date = "2025-04-04";
  };
  mpv-subsearch = {
    pname = "mpv-subsearch";
    version = "9a5cda4fc8f0896cec27dca60a32251009c0e9c5";
    src = fetchFromGitHub {
      owner = "kelciour";
      repo = "mpv-scripts";
      rev = "9a5cda4fc8f0896cec27dca60a32251009c0e9c5";
      fetchSubmodules = false;
      sha256 = "sha256-BRyKJeXWFhsCDKTUNKsp+yqYpP9mzbaZMviUFXyA308=";
    };
    date = "2019-01-24";
  };
  niri = {
    pname = "niri";
    version = "1ab1737653d8727c63252fb569e011c0903a9ace";
    src = fetchFromGitHub {
      owner = "YaLTeR";
      repo = "niri";
      rev = "1ab1737653d8727c63252fb569e011c0903a9ace";
      fetchSubmodules = false;
      sha256 = "sha256-JEpNneZyi8ydU0VVpxrHis2panjmeagFLGAiqigWMbE=";
    };
    date = "2025-12-30";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "093c1a79f58daab358199c4246de50357e5bf462";
    src = fetchFromGitHub {
      owner = "adi1090x";
      repo = "rofi";
      rev = "093c1a79f58daab358199c4246de50357e5bf462";
      fetchSubmodules = false;
      sha256 = "sha256-iUX0Quae06tGd7gDgXZo1B3KYgPHU+ADPBrowHlv02A=";
    };
    date = "2025-07-26";
  };
  rusty-path-of-building = {
    pname = "rusty-path-of-building";
    version = "v0.2.10";
    src = fetchFromGitHub {
      owner = "meehl";
      repo = "rusty-path-of-building";
      rev = "v0.2.10";
      fetchSubmodules = false;
      sha256 = "sha256-odiiYWoBfcnPNfXsxj0gt/ra6Z3zeBQdWRjF7BazffY=";
    };
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "da5b69563c67717c4bb422c9c72cc0cb9baa0632";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "da5b69563c67717c4bb422c9c72cc0cb9baa0632";
      fetchSubmodules = false;
      sha256 = "sha256-LjlcAKlAZ/r4BDdcUGFX+e4LLZRHEH/jCsciKMs4QWg=";
    };
    date = "2025-12-30";
  };
  yazi-time-travel = {
    pname = "yazi-time-travel";
    version = "7e0179e15a41a4a42b6d0b5fa6dd240c9b4cf0d2";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "time-travel.yazi";
      rev = "7e0179e15a41a4a42b6d0b5fa6dd240c9b4cf0d2";
      fetchSubmodules = false;
      sha256 = "sha256-ZZgn5rsBzvZcnDWZfjMBPRg9QUz4FTq5UIPWfnwXHQs=";
    };
    date = "2025-02-14";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "2025.12.08";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "2025.12.08";
      fetchSubmodules = false;
      sha256 = "sha256-y06MDP+CrlHGrell9hcLOGlHp/gU2OOxs7can4hbj+g=";
    };
  };
}
