# This file was generated by nvfetcher, please do not modify it manually.
{ fetchFromGitHub, dockerTools }:
{
  mpv-dynamic-crop = {
    pname = "mpv-dynamic-crop";
    version = "c79a46ba03631eb2a9b4f598aab0b723f03fc531";
    src = fetchFromGitHub {
      owner = "Ashyni";
      repo = "mpv-scripts";
      rev = "c79a46ba03631eb2a9b4f598aab0b723f03fc531";
      fetchSubmodules = false;
      sha256 = "sha256-W4Dj2tyJHeHLqAndrzllKs4iwMe3Tu8rfzEGBHuke6s=";
    };
    date = "2023-12-22";
  };
}
