# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-dynamic-crop = {
    pname = "mpv-dynamic-crop";
    version = "7bb1fa3a2a8193e15c88ed0b103224fa5fb41719";
    src = fetchFromGitHub {
      owner = "Ashyni";
      repo = "mpv-scripts";
      rev = "7bb1fa3a2a8193e15c88ed0b103224fa5fb41719";
      fetchSubmodules = false;
      sha256 = "sha256-5zxFbydchQwQj+CoOoEaS+cQhA8csF9EsBIDcPNDcPc=";
    };
    date = "2023-10-12";
  };
}
