# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-subsearch = {
    pname = "mpv-subsearch";
    version = "9a5cda4fc8f0896cec27dca60a32251009c0e9c5";
    src = fetchFromGitHub {
      owner = "kelciour";
      repo = "mpv-scripts";
      rev = "9a5cda4fc8f0896cec27dca60a32251009c0e9c5";
      fetchSubmodules = false;
      sha256 = "sha256-BRyKJeXWFhsCDKTUNKsp+yqYpP9mzbaZMviUFXyA308=";
    };
    date = "2019-01-24";
  };
}
