#!/bin/sh

termclass="Alacritty"
chromeclass="Brave-browser"

webdesktop=1
filedesktop=3
nemodesktop=4
sectermdesktop=7
listdesktop=8
chatdesktop=9
dldesktop=10

openterm() {
    # xst
    # $TERMINAL -n $@

    # alacritty
    $TERMINAL --class $termclass,$@
}

# setups for different machines
if xrandr | grep "eDP1 connected"; then
    xwallpaper --output 'eDP1' --zoom '/home/iynaix/Pictures/Wallpapers/gits-catppuccin-1920.png'

    # remap caps lock to mod tap Esc and Super
    xmodmap ~/.xmodmap
    xcape -e 'Super_R=Escape' -t 200
else
    if xrandr | grep "HDMI-0 connected"; then
        xwallpaper --output 'DP-2' --zoom '/home/iynaix/Pictures/Wallpapers/gits-catppuccin-3440.png' --output 'DP-0.8' --zoom '/home/iynaix/Pictures/Wallpapers/gits-catppuccin-2560.png' --output 'HDMI-0' --zoom '/home/iynaix/Pictures/Wallpapers/gits-catppuccin-1920.png'
    else
        xwallpaper --output 'DP-2' --zoom '/home/iynaix/Pictures/Wallpapers/gits-catppuccin-3440.png' --output 'DP-0.8' --zoom '/home/iynaix/Pictures/Wallpapers/gits-catppuccin-2560.png'
    fi
fi

# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sxhkd -c "$HOME/.config/bspwm/sxhkdrc" "$HOME/.config/bspwm/bspwm_sxhkdrc" &
fi

# init keyring
gnome-keyring-daemon --start &
export GNOME_KEYRING_CONTROL=/run/user/1000/keyring
export SSH_AUTH_SOCK=/run/user/1000/keyring/ssh

# (re)start picom
pgrep picom && pkill picom || picom -b

# web browsers
bspc rule -a $chromeclass -o desktop=$webdesktop &
brave --profile-drectory=Default &

bspc rule -a $chromeclass -o desktop=$webdesktop follow=on &
brave --incognito &

bspc rule -a $termclass:dltxt -o desktop=$dldesktop &
openterm dltxt -e nvim ~/Desktop/yt.txt &

bspc rule -a $termclass:dlterm -o desktop=$dldesktop &
openterm dlterm &

# nemo desktop
bspc rule -a Nemo:nemo -o desktop=$nemodesktop &
nemo &

# chat desktop
firefox-developer-edition --class=ffchat https://discordapp.com/channels/@me https://web.whatsapp.com http://localhost:9091 &

# terminal desktops
bspc rule -a $termclass:ranger -o desktop=$filedesktop &
openterm ranger -e ranger ~/Downloads &

bspc rule -a $termclass:initialterm -o desktop=$sectermdesktop follow=on &
openterm initialterm &

# subscribe to bspc events
# note: this must be the last line in the file!
bspc subscribe all | bspc-events
