# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-cut = {
    pname = "mpv-cut";
    version = "3b18f1161ffb2ff822c88cb97e099772d4b3c26d";
    src = fetchFromGitHub {
      owner = "familyfriendlymikey";
      repo = "mpv-cut";
      rev = "3b18f1161ffb2ff822c88cb97e099772d4b3c26d";
      fetchSubmodules = false;
      sha256 = "sha256-c4NHJM1qeXXBz8oyGUzS9QiAzRYiNKjmArM1K0Q2Xo0=";
    };
    date = "2023-11-22";
  };
}
