# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rofi-themes = {
    pname = "rofi-themes";
    version = "d6ae47205a375108f7fc7c96b6dc9d647951dcad";
    src = fetchFromGitHub {
      owner = "adi1090x";
      repo = "rofi";
      rev = "d6ae47205a375108f7fc7c96b6dc9d647951dcad";
      fetchSubmodules = false;
      sha256 = "sha256-XJP7lKSataPkQayVzUElrUnOBJhhaZtrbIZZsRUX/Ew=";
    };
    date = "2025-07-15";
  };
}
