# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rofi-themes = {
    pname = "rofi-themes";
    version = "b76c16b2b7c465d7b082e11e5210fcd10c6683a7";
    src = fetchFromGitHub {
      owner = "adi1090x";
      repo = "rofi";
      rev = "b76c16b2b7c465d7b082e11e5210fcd10c6683a7";
      fetchSubmodules = false;
      sha256 = "sha256-9IHENxHQors2z3aYj/xToZD79Gmi1aqlE3QnKnvOT9A=";
    };
    date = "2025-04-18";
  };
}
