# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rofi-themes = {
    pname = "rofi-themes";
    version = "3f2275ab8f9dbb697c7387a20a78a3da196c302a";
    src = fetchFromGitHub {
      owner = "adi1090x";
      repo = "rofi";
      rev = "3f2275ab8f9dbb697c7387a20a78a3da196c302a";
      fetchSubmodules = false;
      sha256 = "sha256-slq48vZlVLmFn4K+ET0uZeFQJYr7+lGxAzvvPHXj/NU=";
    };
    date = "2024-09-09";
  };
}
