# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  path-of-building = {
    pname = "path-of-building";
    version = "v2.48.2";
    src = fetchFromGitHub {
      owner = "PathOfBuildingCommunity";
      repo = "PathOfBuilding";
      rev = "v2.48.2";
      fetchSubmodules = false;
      sha256 = "sha256-KMj+aS+xd96pt1NhqL3CBKj83ZfiX2npmJtwUFa00qU=";
    };
  };
  swww = {
    pname = "swww";
    version = "9a012646e66420ab8058b9f595cdfa0c14625755";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "9a012646e66420ab8058b9f595cdfa0c14625755";
      fetchSubmodules = false;
      sha256 = "sha256-b7rgfW6GSNwC0bolnlDDw8SV8ZgiChlbMeQ3Q1YfA4E=";
    };
  };
  wallust = {
    pname = "wallust";
    version = "3091f71ef406fddd0079bc6d51845313ca35618a";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust.git";
      rev = "3091f71ef406fddd0079bc6d51845313ca35618a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-efhpbSGTogFLEnnJnL0Zu9/GBC2qr/RjixsQWid+bBo=";
    };
    date = "2024-08-14";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "2024.08.06";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "2024.08.06";
      fetchSubmodules = false;
      sha256 = "sha256-NjsP8XbaLs4RTXDuviN1MEYQ2Xv//P5MPXIym1S4hEw=";
    };
  };
}
