# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  path-of-building = {
    pname = "path-of-building";
    version = "v2.52.3";
    src = fetchFromGitHub {
      owner = "PathOfBuildingCommunity";
      repo = "PathOfBuilding";
      rev = "v2.52.3";
      fetchSubmodules = false;
      sha256 = "sha256-hwluSZGYRMN32dSLIe8Cs6l6R84V5fNCuHYtoc7+b00=";
    };
  };
  swww = {
    pname = "swww";
    version = "3e2e2ba8f44469a1446138ee97d2988e22b093bf";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "3e2e2ba8f44469a1446138ee97d2988e22b093bf";
      fetchSubmodules = false;
      sha256 = "sha256-XBwgv80YfLZ70XYVEnR0nA7Rz5jP241D5FiwrTg7tDk=";
    };
    date = "2025-01-17";
  };
  wallust = {
    pname = "wallust";
    version = "70817f238fb1c7b7fb2830690b399317269dfeef";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust";
      rev = "70817f238fb1c7b7fb2830690b399317269dfeef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-L0HnGfFAoFRSOUaUJmzs27fP0weUSaVzgB2Lu2TdYag=";
    };
    date = "2025-03-01";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "5186af7984aa8cb0550358aefe751201d7a6b5a8";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "5186af7984aa8cb0550358aefe751201d7a6b5a8";
      fetchSubmodules = false;
      sha256 = "sha256-Cw5iMljJJkxOzAGjWGIlCa7gnItvBln60laFMf6PSPM=";
    };
    date = "2025-02-21";
  };
  yazi-time-travel = {
    pname = "yazi-time-travel";
    version = "7e0179e15a41a4a42b6d0b5fa6dd240c9b4cf0d2";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "time-travel.yazi";
      rev = "7e0179e15a41a4a42b6d0b5fa6dd240c9b4cf0d2";
      fetchSubmodules = false;
      sha256 = "sha256-ZZgn5rsBzvZcnDWZfjMBPRg9QUz4FTq5UIPWfnwXHQs=";
    };
    date = "2025-02-14";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "2025.02.19";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "2025.02.19";
      fetchSubmodules = false;
      sha256 = "sha256-otgB9rrv6mgqLdRCuxhZirl5npNQhIKdzFLBrfPer4M=";
    };
  };
}
