# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hypridle = {
    pname = "hypridle";
    version = "4395339a2dc410bcf49f3e24f9ed3024fdb25b0a";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hypridle";
      rev = "4395339a2dc410bcf49f3e24f9ed3024fdb25b0a";
      fetchSubmodules = false;
      sha256 = "sha256-ZSn3wXQuRz36Ta/L+UCFKuUVG6QpwK2QmRkPjpQprU4=";
    };
    date = "2024-03-11";
  };
  hyprlock = {
    pname = "hyprlock";
    version = "87fce7923fef1143b3a473abb2fc873e67664475";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprlock";
      rev = "87fce7923fef1143b3a473abb2fc873e67664475";
      fetchSubmodules = false;
      sha256 = "sha256-d0Shu3dqdJj9QKR3dnE4Mh8t66hUlfLGZl+9A9JsoI8=";
    };
    date = "2024-03-24";
  };
  path-of-building = {
    pname = "path-of-building";
    version = "v2.41.0";
    src = fetchFromGitHub {
      owner = "PathOfBuildingCommunity";
      repo = "PathOfBuilding";
      rev = "v2.41.0";
      fetchSubmodules = false;
      sha256 = "sha256-XoRoKvlfBtlKyur1AZ+VjYc5URyX2/fof05h6Vs+vok=";
    };
  };
  swww = {
    pname = "swww";
    version = "dcf0d4e481b13c19f2490d730cb45c03d4e8b77b";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "dcf0d4e481b13c19f2490d730cb45c03d4e8b77b";
      fetchSubmodules = false;
      sha256 = "sha256-HfK9AOTsTO0JnrD6e6g/LtwukOjDhf9ZeC6/TmNZqDc=";
    };
    date = "2024-03-23";
  };
  wallust = {
    pname = "wallust";
    version = "104d99fcb4ada743d45de76caa48cd899b021601";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust.git";
      rev = "104d99fcb4ada743d45de76caa48cd899b021601";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-gGyxRdv2I/3TQWrTbUjlJGsaRv4SaNE+4Zo9LMWmxk8=";
    };
    date = "2024-03-08";
  };
}
