# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-sub-select = {
    pname = "mpv-sub-select";
    version = "31f5bf53e7f3b833862c4dfde0993d13253d95db";
    src = fetchFromGitHub {
      owner = "CogentRedTester";
      repo = "mpv-sub-select";
      rev = "31f5bf53e7f3b833862c4dfde0993d13253d95db";
      fetchSubmodules = false;
      sha256 = "sha256-P5c5sDXWR2NJ6LSIn+0Rb57f17DC5nY5Hl7Nz0g1524=";
    };
    date = "2024-04-19";
  };
}
