# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-sub-select = {
    pname = "mpv-sub-select";
    version = "9b0043ba6042ba01fdd2533281313b70cbc98be4";
    src = fetchFromGitHub {
      owner = "CogentRedTester";
      repo = "mpv-sub-select";
      rev = "9b0043ba6042ba01fdd2533281313b70cbc98be4";
      fetchSubmodules = false;
      sha256 = "sha256-ZLWwkwrFaOg7PnuC23VaZ0P3zMhm1JmVf0eH9lqO0BY=";
    };
    date = "2024-08-31";
  };
}
