# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-deletefile = {
    pname = "mpv-deletefile";
    version = "9bdce0050144cb24f92475f7bdd77180e0e4c26b";
    src = fetchFromGitHub {
      owner = "zenyd";
      repo = "mpv-scripts";
      rev = "9bdce0050144cb24f92475f7bdd77180e0e4c26b";
      fetchSubmodules = false;
      sha256 = "sha256-9P/8q/OZXfaJMS08acQP4h3/zUA5mKRQee0JmkXcz1w=";
    };
    date = "2024-02-12";
  };
}
