# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-deletefile = {
    pname = "mpv-deletefile";
    version = "7100d19d18d111ce77fc9e6e8947c0d542a86397";
    src = fetchFromGitHub {
      owner = "zenyd";
      repo = "mpv-scripts";
      rev = "7100d19d18d111ce77fc9e6e8947c0d542a86397";
      fetchSubmodules = false;
      sha256 = "sha256-hpLZDtt5q18aZ8d9LHfT852wtBosKUTJ7Bx+cbjBLcg=";
    };
    date = "2024-01-26";
  };
}
