# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-deletefile = {
    pname = "mpv-deletefile";
    version = "19ea069abcb794d1bf8fac2f59b50d71ab992130";
    src = fetchFromGitHub {
      owner = "zenyd";
      repo = "mpv-scripts";
      rev = "19ea069abcb794d1bf8fac2f59b50d71ab992130";
      fetchSubmodules = false;
      sha256 = "sha256-OBCuzCtgfSwj0i/rBNranuu4LRc47jObwQIJgQQoerg=";
    };
    date = "2022-04-22";
  };
}
