# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  helium-arm64 = {
    pname = "helium-arm64";
    version = "0.5.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.5.2.1/helium-0.5.2.1-arm64.AppImage";
      sha256 = "sha256-gWJ6xuHeP+tmduspPeRG6sbeQpihFWW6TSr/2zPJGjM=";
    };
  };
  helium-x86_64 = {
    pname = "helium-x86_64";
    version = "0.5.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.5.2.1/helium-0.5.2.1-x86_64.AppImage";
      sha256 = "sha256-3h0GMMl58NX+PuZRwmksOvlwPuZZwiQJdM5YXkaxlDk=";
    };
  };
}
