#! /bin/sh
bspc rule -r "*"

# laptop specific setup
if xrandr | grep "eDP1 connected"; then
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10

    window_gap=4
    padding=4
# desktop specific setup
else
    # triple screen
    if xrandr | grep "HDMI-0 connected"; then
        bspc monitor HDMI-0 -d 9 10
        bspc monitor %DP-0.8 -d 6 7 8
        bspc monitor DP-2 -d 1 2 3 4 5

        window_gap=8
        padding=8
    # dual screen
    else
        bspc monitor %DP-0.8 -d 6 7 8 9 10
        bspc monitor DP-2 -d 1 2 3 4 5

        window_gap=8
        padding=8
    fi
fi

normal="#30302f"
focused="#4491ed"
bar_height=30
border_width=2

bspc config automatic_scheme longest_side

# borders and gaps
bspc config border_width         2
bspc config active_border_color  $normal
bspc config normal_border_color  $normal
bspc config focused_border_color $focused

bspc config window_gap           $window_gap
bspc config top_padding          $(( padding + bar_height ))
bspc config left_padding         $padding
bspc config right_padding        $padding
bspc config bottom_padding       $padding

bspc config presel_feedback_color   $focused
bspc config split_ratio             0.5
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

# smart gaps
bspc config single_monocle          true
bspc config borderless_monocle      false
bspc config gapless_monocle         true
bspc config top_monocle_padding     0
bspc config right_monocle_padding   0
bspc config bottom_monocle_padding  0
bspc config left_monocle_padding    0

# handle the mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_motion_interval 7ms

# handle unplugging monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# custom external rules
bspc config external_rules_command ~/bin/bspwm_external_rules

bspc rule -a ffchat desktop=9
bspc rule -a Transmission-gtk desktop=10
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Peek state=floating
bspc rule -a streamdeck state=floating

xrdb ~/.Xresources
# pidof bspswallow || bspswallow &

# polybar
~/.config/polybar/launch.sh &

# mpd
# [ ! -s ~/.config/mpd/pid ] && mpd

# ping -c1

[[ ! $(pidof -x brave) ]] && ~/.config/bspwm/bspwm_start &
# until ping -c1 www.google.com >/dev/null 2>&1
# do
# done
