# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-nextfile = {
    pname = "mpv-nextfile";
    version = "b8f7a4d6224876bf26724a9313a36e84d9ecfd81";
    src = fetchFromGitHub {
      owner = "jonniek";
      repo = "mpv-nextfile";
      rev = "b8f7a4d6224876bf26724a9313a36e84d9ecfd81";
      fetchSubmodules = false;
      sha256 = "sha256-Ad98iUbumhsudGwHcYEVTV6ye6KHj5fHAx8q90UQ2QM=";
    };
    date = "2023-08-09";
  };
}
