# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hyprNStack = {
    pname = "hyprNStack";
    version = "4a3c707ab81c50170de6bbdf6809b470c987cabf";
    src = fetchFromGitHub {
      owner = "zakk4223";
      repo = "hyprNstack";
      rev = "4a3c707ab81c50170de6bbdf6809b470c987cabf";
      fetchSubmodules = false;
      sha256 = "sha256-OIT+Z4ixQ9jrjLkJXrQGI5jTKTddqvZp6d2BQ3ubqbg=";
    };
  };
}
