# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hyprNStack = {
    pname = "hyprNStack";
    version = "803d74889adb065d4051d1505cffeedbfd701780";
    src = fetchFromGitHub {
      owner = "zakk4223";
      repo = "hyprNstack";
      rev = "803d74889adb065d4051d1505cffeedbfd701780";
      fetchSubmodules = false;
      sha256 = "sha256-QvoUdEHUT+lV6D+RGKAwA00DPboTmPT0SMwD0oTscgs=";
    };
  };
}
