# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ravu = {
    pname = "ravu";
    version = "bfcf48a15562eda973f9713041a60eb31516586a";
    src = fetchFromGitHub {
      owner = "bjin";
      repo = "mpv-prescalers";
      rev = "bfcf48a15562eda973f9713041a60eb31516586a";
      fetchSubmodules = false;
      sha256 = "sha256-m3S/WX6AZzD3Em61V7OJ7PK2InWpsu7xzScWoc/vljA=";
    };
    date = "2024-01-10";
  };
}
