# This file was generated by nvfetcher, please do not modify it manually.
{ fetchFromGitHub, dockerTools }:
{
  ravu = {
    pname = "ravu";
    version = "b3f0a59d68f33b7162051ea5970a5169558f0ea2";
    src = fetchFromGitHub {
      owner = "bjin";
      repo = "mpv-prescalers";
      rev = "b3f0a59d68f33b7162051ea5970a5169558f0ea2";
      fetchSubmodules = false;
      sha256 = "sha256-KfCFU3fa8Fr5G5zVqKS35CJBzTYMY72kep8+Kd0YIu4=";
    };
    date = "2024-01-11";
  };
}
