# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ravu = {
    pname = "ravu";
    version = "3f24e7c53085854d122bb5d6629d1d503ba29e35";
    src = fetchFromGitHub {
      owner = "bjin";
      repo = "mpv-prescalers";
      rev = "3f24e7c53085854d122bb5d6629d1d503ba29e35";
      fetchSubmodules = false;
      sha256 = "sha256-Ewk2mjw6gAolrkzg+4DmVpOxRJDG6vOzzoQHF6668T8=";
    };
    date = "2023-09-13";
  };
}
